version: '3.7'
services:
    database:
        image: mysql
        volumes:
            - ./db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "swati"
            MYSQL_DATABASE: utilitystorage_db
        ports:
            - 3307:3306